services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - test-net
    volumes:
      - test-db-data:/var/lib/postgresql/data

volumes:
  test-db-data:

networks:
  test-net:
